Since the contructor throws an exception which is not caught, this makes the Demo object not completely constructed. Because of this, no destructor for said object can be called. To ensure that the object is properly destructed, we must ensure that it is firstly properly constructed. In order to do so, a second catch clause has been added in the constructor's body. This is needed because exceptions in a constuctor's body can only be managed at a more shallow level of code. This change makes it so the object is fully constructed and can be destructed at the end of the program.
